<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="U6043535-TPL-A" name="Test-method test" tests="2" failures="1" timestamp="20 Oct 2017 09:49:05 GMT" time="19.137" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="com.TrustTaxQA.SmokeTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.TrustTaxQA.BaseClass.afterMethod(BaseClass.java:104)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.TrustTaxQA.SmokeTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="com.TrustTaxQA.SmokeTest">
    <skipped/>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="AccounttrustTaxLogin" time="0.002" classname="com.TrustTaxQA.SmokeTest">
    <failure type="java.lang.Exception">
      <![CDATA[java.lang.Exception
	at com.TrustTaxQA.SmokeTest.AccounttrustTaxLogin(SmokeTest.java:30)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- AccounttrustTaxLogin -->
  <testcase name="OpenAccount" time="0.001" classname="com.TrustTaxQA.SmokeTest">
    <skipped/>
  </testcase> <!-- OpenAccount -->
</testsuite> <!-- Test-method test -->
